config/routes.rb
ChefCity::Application.routes.draw do

  match 'login' => 'users#login'
  match 'logout' => 'users#logout'
  resources :recipes, :articles
  resource :users, :on => :member
  namespace :admin do
    resources :users do
      resources :recipes, :articles
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/user.rb
require "digest"
class User < ActiveRecord::Base
  validates :email, :uniqueness=>true, :presence=>true
  validates :password, :presence=>true

  def password_matches?(candidate_password)
    puts "candidate #{candidate_password} salt: #{self.salt} password: #{self.password}"
    puts "digest: #{Digest::MD5.hexdigest(self.salt + candidate_password)}"
    self.password == Digest::MD5.hexdigest(self.salt + candidate_password)

  end

  def encrypt_password
    if (!self.salt)
      self.salt = generate_salt
      puts "encrypting: #{Digest::MD5.hexdigest(self.salt + self.password)} with salt: #{self.salt} and pass #{self.password}"
      self.password = Digest::MD5.hexdigest(self.salt + self.password)
    end

  end

  def save
    encrypt_password
    super
  end

  private
  def generate_salt
    salt = ""
    1.upto(5) do
      salt+= rand(9).to_s
    end
    salt
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :current_user
  protect_from_forgery
  helper :all


  private
  def login_required
    if !session[:user]
      redirect_to login_path
      false
    end
  end

  def current_user
    logger.debug "running current_user session[:user] #{session[:user]}"
    if session[:user]
      @current_user ||= User.find(session[:user])
    else
      false
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :js, :html

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end
  
  def create
    if request.post? and params[:article]
      article = Article.new(params[:article])
      if article.save
        @save_status = "Success!"
      else
        @save_status = "Something went wrong! Please try again later!"
    end
      respond_with(@save_status, :layout=> !request.xhr?)
    end
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  respond_to :js, :html

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    if request.post? and params[:recipe]
      recipe = Recipe.new(params[:recipe])
      if recipe.save
        @save_status = "Success!"
      else
        @save_status = "Something went wrong! Please try again later!"
    end
      respond_with(@save_status, :layout=> !request.xhr?)  
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :js, :html
  
  def create
    @user = User.new(params[:user])
    if @user.save
      @login_status = "Success!"
    else
      @login_status = "Something went wrong! Please try again later!"
    end
    respond_with(@login_status, :layout=> !request.xhr?)   
  end


  def new
    @user = User.new   
  end


  def login
    if request.post? and params[:email]
      @current_user = User.where(:email => params[:email]).first
      logger.debug "email: #{params[:email]} current_user id: #{@current_user.id}"
      if @current_user and @current_user.password_matches?(params[:password])
        session[:user] = @current_user.id
      else
        flash[:notice] = "Wrong email/password combination. Please try again."
      end

      logger.debug "login set session id to #{session[:user]}"
      redirect_to :back
    end
  end

  def logout
    if session[:user]
      reset_session
    end
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    if session[:user]
      @current_user ||= User.find(session[:user])
    else
      false
    end
  end
end

app/views/articles/_article.html.haml
%h2
  = article.title
= article.content

app/views/articles/create.js.haml
$('#save_status').html("#{@save_status}")

app/views/articles/index.html.haml
#articles
  %h2
    Blog posts
  #content
    %div{'style'=>'{float:right;}'}
      = link_to 'Create_new', new_article_path
    - @articles.each do |article|
      = link_to article.title, article_path(article)

app/views/articles/new.html.haml
#articles
  #main
    %h2
      Write a Blog Post
    = form_for @article, :remote=>true, :method=>:post do |f|
      %label
        Title
        .label_desc
          The title of your post
      = f.text_field :title
      %label
        Content
        .label_desc
          The meat of your post
      = f.text_area :content
      .submit
        = f.submit
    #save_status

app/views/articles/show.html.haml
#articles
  #content
    = render :partial=>'article', :locals=>{:article=>@article}

app/views/layouts/application.html.haml
%html
%head
  %title= yield(:title) || 'Chef City'
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"

%body
  = render :partial=>'shared/header'
  = yield

app/views/recipes/_recipe.html.haml
%h3
  = recipe.name
= recipe.contents
%hr

app/views/recipes/create.js.haml
$('#save_status').html("#{@save_status}")

app/views/recipes/index.html.haml
#recipes
  %h2
    Recipes
  #content
    %div{'style'=>'{float:right;}'}
      = link_to 'Create_new', new_recipe_path
    = render :partial=>'recipe', :collection=>@recipes

app/views/recipes/new.html.haml
#recipes
  #main
    %h2
      Create a Recipe
    = form_for @recipe, :remote=>true, :method=>:post do |f|
      %label
        Name
        .label_desc
          The name of the dish
      = f.text_field :name
      %label
        Contents
        .label_desc
          The ingredients and instructions
      = f.text_area :contents
      .submit
        = f.submit
    #save_status

app/views/shared/_header.html.haml
#header
  #link
    = link_to 'Article Posts', articles_path
  #link
    = link_to 'Recipes', recipes_path
  - if @current_user
    #user_link
      = link_to 'Logout', logout_path
  - else
    #user_link
      = link_to 'Login', login_path
    #user_link  
      = link_to 'Register', new_users_path

app/views/users/create.js.haml
$('#register_status').html("#{@login_status}")

app/views/users/login.html.haml
%h2
  Login
= form_tag login_path do
  %label
    Email
    .label_desc
      Email you used to register
  = text_field_tag :email
  %label
    Password
    .label_desc
      Password must be at least 8 characters
  = password_field_tag :password
  .submit
    = submit_tag "Login"

app/views/users/new.html.haml
#users
  #main
    %h2
      Make a Chef City account!
    = form_for @user, :remote=>true, :method=>:post do |f|
      %label
        Email
        .label_desc
          Enter your email address
      = f.text_field :email
      %label
        Password
        .label_desc
          Password must be at least 8 characters
      = f.password_field :password
      .submit
        = f.submit
    #register_status